x-service-template: &service-template
  restart: unless-stopped
  extra_hosts:
    - "committer-sidecar:host-gateway"
    - "committer-queryservice:host-gateway"
  networks:
    - test

services:
  issuer:
    <<: *service-template
    hostname: issuer.example.com
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_TYPE: issuer
        PLATFORM: "${PLATFORM:-fabricx}"
    volumes:
      - ./${CONF_ROOT:-conf}/issuer:/conf
    expose:
      - 9101:9001
    ports:
      - 9100:9000/tcp

  endorser1:
    <<: *service-template
    hostname: endorser1.example.com
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_TYPE: endorser
        PLATFORM: "${PLATFORM:-fabricx}"
    volumes:
      - ./${CONF_ROOT:-conf}/endorser1:/conf
      - ./${CONF_ROOT:-conf}/namespace/zkatdlognoghv1_pp.json:/namespace/zkatdlognoghv1_pp.json
    expose:
      - 9301:9001
    ports:
      - 9300:9000/tcp

  owner1:
    <<: *service-template
    hostname: owner1.example.com
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_TYPE: owner
        PLATFORM: "${PLATFORM:-fabricx}"
    volumes:
      - ./${CONF_ROOT:-conf}/owner1:/conf
    expose:
      - 9501:9001
    ports:
      - 9500:9000/tcp

  owner2:
    <<: *service-template
    hostname: owner2.example.com
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_TYPE: owner
        PLATFORM: "${PLATFORM:-fabricx}"
    volumes:
      - ./${CONF_ROOT:-conf}/owner2:/conf
    expose:
      - 9601:9001
    ports:
      - 9600:9000/tcp

  swagger-ui:
    <<: *service-template
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - URL=/swagger.yaml
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/swagger.yaml

# fabric_test is the name of the fabric-samples test network.
# By connecting to it, we can reach the peers at their DNS names
# (e.g. peer0.org1.example.com).
networks:
  test:
    name: fabric_test
    external: true
