#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Verify control node dependencies
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if requests is importable
      ansible.builtin.command: python3 -c "import requests"
      register: check_requests
      failed_when: check_requests.rc != 0
      ignore_errors: true

    - name: Fail if requests is missing
      ansible.builtin.fail:
        msg: >
          The Python package 'requests' is not installed in the Python environment Ansible is using. Run the following to install it:

            python3 -m pip install -r requirements.txt
      when: check_requests.rc != 0

- name: Generate crypto material
  ansible.builtin.import_playbook: hyperledger.fabricx.artifacts.build_crypto_material

- name: Generate genesis block
  ansible.builtin.import_playbook: hyperledger.fabricx.artifacts.build_genesis_block

- name: Build Fabric-X Orderer binaries
  ansible.builtin.import_playbook: hyperledger.fabricx.orderer.build_binaries

- name: Build Fabric-X Committer binaries
  ansible.builtin.import_playbook: hyperledger.fabricx.committer.build_binaries

- name: Build Loadgen binaries
  ansible.builtin.import_playbook: hyperledger.fabricx.loadgen.build_binaries

# Transfer

- name: Transfer Fabric-X Orderer configs
  ansible.builtin.import_playbook: hyperledger.fabricx.orderer.transfer_configs

- name: Transfer Fabric-X Committer configs
  ansible.builtin.import_playbook: hyperledger.fabricx.committer.transfer_configs

- name: Transfer Monitoring configs
  ansible.builtin.import_playbook: hyperledger.fabricx.monitoring.transfer_configs

- name: Transfer Loadgen configs
  ansible.builtin.import_playbook: hyperledger.fabricx.loadgen.transfer_configs

- name: Transfer Fabric-X Orderer binaries
  ansible.builtin.import_playbook: hyperledger.fabricx.orderer.transfer_binaries

- name: Transfer Fabric-X Committer binaries
  ansible.builtin.import_playbook: hyperledger.fabricx.committer.transfer_binaries

- name: Transfer Loadgen configs
  ansible.builtin.import_playbook: hyperledger.fabricx.loadgen.transfer_binaries
