#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Start Fabric-X Orderer
  ansible.builtin.import_playbook: hyperledger.fabricx.orderer.start

- name: Start Fabric-X Committer
  ansible.builtin.import_playbook: hyperledger.fabricx.committer.start

- name: Start Monitoring
  ansible.builtin.import_playbook: hyperledger.fabricx.monitoring.start

- name: Start Loadgen
  ansible.builtin.import_playbook: hyperledger.fabricx.loadgen.start
